import type { Octokit } from "./types.js";
import { COMMENT_MARKER } from "./constants.js";

function buildCommentBody(instructions: string): string {
	return [
		COMMENT_MARKER,
		"## QA Instructions",
		"",
		instructions,
		"",
		"---",
		"*Generated by [QA Instructions Action](https://github.com/BadIdeaFactory/qa-instructions-action)*",
	].join("\n");
}

export async function postOrUpdateComment(
	octokit: Octokit,
	owner: string,
	repo: string,
	pullNumber: number,
	instructions: string,
): Promise<void> {
	const body = buildCommentBody(instructions);

	const comments = await octokit.paginate(octokit.rest.issues.listComments, {
		owner,
		repo,
		issue_number: pullNumber,
	});

	const existing = comments.find((c) => c.body?.includes(COMMENT_MARKER));

	if (existing) {
		await octokit.rest.issues.updateComment({
			owner,
			repo,
			comment_id: existing.id,
			body,
		});
	} else {
		await octokit.rest.issues.createComment({
			owner,
			repo,
			issue_number: pullNumber,
			body,
		});
	}
}
